### ISSUE TITLE
Design and Requirements Discussion

### ISSUE THREAD

**Issue by aak1247** [aak1247/pyvm#1]
Question: what kind of thing should be done in a python version manager?

**Comment by aak1247** [comment]
@Thrimbda I have tried it and it's awesome. But pipenv sometimes may not work well especially when using different envirentment (e.g.python version) in a same directory.

**Comment by Thrimbda** [comment]
That was because you did not install `pyenv`, for it is a optional dependency of `pipenv`.
you'll have to install `pyenv` manually, and after which you can just invoke
```bash
pipenv install --python 3.6.0
```

**Comment by aak1247** [comment]
awesome
